default: &default
  dispatchers:
    - polling_interval: 1
      batch_size: 500
      recurring_tasks:
        # notify_missing_agent_approver:
        #   class: NotifyMissingAgentApproverJob
        #   # args: [42, { status: "custom_status" }]
        #   schedule: "5 0 * * *"
  workers:
    - queues: "*"
      threads: 5
      processes: 1
      polling_interval: 0.1
    - queues: ["real_time", "background"]
      threads: 5
      polling_interval: 0.1
      processes: 3

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
